version: '2'
services:
    displayconfig-app:
        image: displayconfig
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:postgresql://displayconfig-postgresql:5432/DisplayConfig
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8081:8081
    displayconfig-postgresql:
        extends:
            file: postgresql.yml
            service: displayconfig-postgresql
